#!/bin/sh
set -e

sudo apt update
sudo apt upgrade -y

curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
sudo apt install nodejs curl -y

git clone https://github.com/TarteelTamimi/BookManager.git app
cd app && npm install

npm run build

sudo mv app.service /etc/systemd/system

sudo systemctl daemon-reload
sudo systemctl enable app.service
sudo reboot
